### ISSUE TITLE
OpenShift application installation problem (operator 0.9.0)

### ISSUE THREAD

**Issue by denis-ignatenko** [tarantool/tarantool-operator#109]
When installing application in OpenShift environment using the oparator version 0.7.0 and the cartridge chart version 0.9.0, the application starts successfully.
When installing in a bundle of 0.9.0 oparator and 0.9.0 cartridge chart, an error occurs.

Attached operator's log [tarantool-operator.log](https://github.com/tarantool/tarantool-operator/files/7120421/tarantool-operator.log) from the beginning of application installation.

Seems like a lack of rights. Please add OpenShift test.

**Comment by vanyarock01** [comment]
Based on the logs, the error is:
```
roles.tarantool.io \"store\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
```
Which seems to be caused by the next commit: https://github.com/tarantool/tarantool-operator/commit/b326b3bf2efa141dc97b1daedca9a89cdfb16524

Finalizer is a subresource that is controlled by the [admission](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement) controller. So you need to grant update verb for `roles/finalizers`.

I'm not sure if this helps since I don't have access to openshift cluster, but it seems to be true:
```yaml
# .../your-operator-chart-dir/../templates/role.yaml
...
- apiGroups:
  - tarantool.io
  resources:
  - roles/finalizers # this line should be added
```
