### ISSUE TITLE
Add TARANTOOL_PROBE_URI_TIMEOUT to env in cartridge helm chart template

### ISSUE THREAD

**Issue by vanyarock01** [tarantool/tarantool-operator#23]
```yaml
env:
    - name: TARANTOOL_PROBE_URI_TIMEOUT
      value: "60"
    ...
```
Required for DNS resolution.
