### ISSUE TITLE
After restart minikube, tarantool cluster cannot be configured

### ISSUE THREAD

**Issue by vanyarock01** [tarantool/tarantool-operator#32]
Dependencies:
* *minikube* version: v1.12.3
* *tarantool/tarantool-operator* chart version: 0.0.5
* *tarantool/cartridge* chart version: 0.0.5

Step to reproduce:
1. Run minikube:  `minikube start`
2. Install `tarantool-operator` and `cartridge` app.
3. Enter into any tarantool app docker container: `kubectl -n tarantool exec -it routers-0-0 /bin/bash` and check volume:
    ```
    bash-4.4$ ls /var/lib/tarantool/test-app.routers-0-0/
    00000000000000000000.snap  00000000000000000000.xlog  config  config.backup
    bash-4.4$
    ```

4. Restart minikube
    ```
    minikube stop
    minikube start
    ``` 
5. Wait until the cluster is **Ready**. For check execute: `kubectl -n tarantool describe clusters.tarantool.io app-name` and find line with *State*.
    ```yaml
    ...
    Spec:
      Selector:
        Match Labels:
          tarantool.io/cluster-id:  test-app
    Status:
      State:  Ready
    Events:   <none>

6. Move to cartridge web-app
![image](https://user-images.githubusercontent.com/23562374/94453474-63361b80-01b9-11eb-8012-c5a86b4315a1.png)
7. Enter into any tarantool app docker container: `kubectl -n tarantool exec -it routers-0-0 /bin/bash` and check data directory:
    ```
    bash-4.4$ ls /var/lib/tarantool/test-app.routers-0-0/
    bash-4.4$
    ```
