### ISSUE TITLE
Make RoleConfig mergeable in Cartridge helm chart

### ISSUE THREAD

**Issue by vanyarock01** [tarantool/tarantool-operator#44]
Now the `RoleConfig` is array of role object. This does not allow merging custom defined values.
For example:
```yaml
RoleConfig:
- RoleName: firstRole
  params: values
  ...
- RoleName: secondRole
  params: values
  ...
```
I suggest using RoleName as a key to the role object:
```yaml
RoleConfig:
  firstRole:
    params: values
    ...
  secondRole:
    params: values
  ...
```
