### ISSUE TITLE
Join error

### ISSUE THREAD

**Issue by chelsEg** [tarantool/tarantool-operator#75]
Hello.

Sometime in operator log i see errors like this:

```
{
   "level":"error",
   "ts":1612859086.4840052,
   "logger":"controller_cluster",
   "msg":"Join error",
   "Request.Namespace":"dmp-base-stage",
   "Request.Name":"dmp-cluster",
   "error":"Post http://x.x.x.x:8081/admin/api: dial tcp x.x.x.x:8081: connect: connection refused",
   "stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/tarantool/tarantool-operator/pkg/controller/cluster.(*ReconcileCluster).Reconcile\n\t/app/pkg/controller/cluster/cluster_controller.go:328\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/internal/controller/controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:88"
}
```

My RoleConfig:

```
RoleConfig:
  - RoleName: storage
    ReplicaCount: 2
    ReplicaSetCount: 1
    DiskSize: 5Gi
    CPUallocation: 0.25
    MemtxMemoryMB: 1024
    RolesToAssign:
      - vshard-router
      - vshard-storage
      - crud-router
      - crud-storage
      - metrics
      - migrator
```

**Operator version: 0.0.8**
**Tarantool version in docker image: 2.6.2**
