### ISSUE TITLE
Cannot verify user is non-root

### ISSUE THREAD

**Issue by vanyarock01** [tarantool/tarantool-operator#83]
I'm trying to deploy an application with non-privileged (any non-root user) containers:
```
Error: container has runAsNonRoot and image has non-numeric user (tarantool), cannot verify user is non-root
```

**Comment by vanyarock01** [comment]
To fix it, configure the security context in cartridge chart:
```yaml
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
```
